### ISSUE TITLE
p4est build from source

### ISSUE THREAD

**Issue by tjhei** [koecher/candi#21]
Building p4est from git source doesn't work for me (configure.ac etc). Is there a reason you are not using the tarball? (like https://github.com/tjhei/candi/blob/master/deal.II/packages/p4est.package)

If there is a reason to keep it this way for some platform, how about we add a package "p4est-tarball" we can use on the platforms where this works? If yes, I can prepare a PR.

**Comment by tjhei** [comment]
Sorry, correct link is https://github.com/tjhei/candi/blob/experimenting/deal.II/packages/p4est.package

**Comment by koecher** [comment]
The reason for this draws back to a broken link from the original p4est website. There was no direct link or even a hint for finding tarballs on https://p4est.github.io/release/
I would like to use the tarballs, since this avoids a lot of compilation issues I simply do not want to have. (bootstrapping for instance).
Can you make a PR?

**Comment by tjhei** [comment]
if you go to http://www.p4est.org/ there is a link called "latest release tarball".

**Comment by tjhei** [comment]
see #30.

**Comment by koecher** [comment]
closed with final merge of #30
