### ISSUE TITLE
PARAMETER_GUI=OFF

### ISSUE THREAD

**Issue by davydden** [koecher/candi#34]
i think its better to turn it off.
I had a configuration error related to Qt, others may also have, i supposed.

**Comment by tjhei** [comment]
Even better: don't specify that option at all.

**Comment by davydden** [comment]
i couldn't actually found where is it specified inside Candi, but adding
```
CONFOPTS="${CONFOPTS} \
-D PARAMETER_GUI=OFF \
"
```
to `dealii.package` sorted it out.

**Comment by tjhei** [comment]
I have that on my branch already but forgot to make a PR (https://github.com/tjhei/candi/commit/8a1974fea38869a6beb39402239d25a32ff9cb59)

**Comment by Rombur** [comment]
@davydden all the parameters are defined in project-deal.II.cfg You can turn off ```PARAMETER_GUI``` by turning off ```-D DEAL_II_COMPONENT_PARAMETER_GUI=ON```

**Comment by davydden** [comment]
by default it's better to have it off

**Comment by koecher** [comment]
For the linux cluster platform, we shall put it to off. For desktop editions I find it more useful to have it on by default, I and some of my colleagues use it.
Candi is designed to have as much as possible swichted on by default, so that a starting user does not have to worry about a missing feature. Later on, one can tweak a personal "local.cfg", which is prefered over "candi.cfg". This is somewhere documented within the "dorsal" part (cf. USAGE file).
I need to update the documentation soon.
The short variant can be found in the repo view (Readme.md / online view: https://github.com/koecher/candi)

**Comment by koecher** [comment]
Okay, I've switched off the parameter gui by default, but left the option in the DEAL_CONFOPTS.
