### ISSUE TITLE
Joining forces of the complete deal.II contributors community for setting up a deal.II installer

### ISSUE THREAD

**Issue by koecher** [koecher/candi#49]
@tjhei @Rombur 
The discussions of the PR #47 and the Issue #24 and several more discussions leads me to point out again that we waste massively our spare research time for making (in this sense candi) to work for most usability.

We already had a lot of discussions on workshops (e.g. PDESoft 2014) and also on the google group (thread of @Rombur ) for a general installer for the deal.II toolchain.

To my best knowlegde, we have a lot of contributors to the discussions, but we do not join our forces since most of the current installers works only for some limited, but personally prefered, solutions (e.g. only supporting ubuntu/debian by tweaking or having restrictions for generality (candi).

I'll think the principical authors of deal.II should discuss carefully this issue and then should make clear to the deal.II community which is (from their point of view) the best starting point in developing a deal.II installer. Then we would be able to join our forces to work on the same problem.

**Comment by tjhei** [comment]
Hey Uwe,

I guess I should explain a bit. @Rombur and I have been evaluating different technologies for making a deal.II installer. I have looked at different solutions (hashdist, linuxbrew, candi, conda, from scratch, probably more?) and we have been trying them out. We haven't made a final decision yet, but candi seems to 95% of where we want to go for now. One of the bonuses is that it is considerably more simple and hackable than the alternatives. I don't think we need a super powerful and flexible userland package manager. A simpler system like candi seems a lot more attractive to me.

In the end it probably makes sense to have a separate repository so we can control the install experience, but I don't want to develop a separate fork of candi (or any other project for that matter). Otherwise, a lot of effort would go to waste and we won't be able to profit from the upstream development.

I understand that candi is your project and ultimately you need to decide where you want it to go. I hope you didn't mind my suggestions, contributions, and comments so far. If something doesn't fit into your agenda, you are welcome to tell us that straight up. 

Regarding more concrete things I would like to see (either inside candi or as part of a small installer script that would call candi):
- Generation of a simple, source-able environment.sh that exports directories of installed libraries (TRILINOS_DIR, DEAL_II_DIR, ...)
- Some way to select between minimal/default/everything regarding dependencies. I don't think there needs to be a way to en/disable individual packages, though. Let's keep it simple.
- Select mpicxx, etc. automatically if they exist and the user is not setting them, because this the right thing to do on nearly every platform.

**Comment by koecher** [comment]
Thank you Timo for your explanations. I think we are talking mostly about the same thing.

By forking I mean a only forward way, no comeback.
We need to make a lot of specific decisions for deal.II, which are not good in the sense of a standard linux installer tool.

I'm also not willing to implement a package manager, but we may need to think about in which way we are currently disabling packages to make your idea of min/default/everything possible.

Regarding generation of source-able files, I'm not familiar with them, but I already build the similar modulefile at the bottom of the dealii.package. Extendening this approach should be easy.

**Comment by koecher** [comment]
Dear Timo (@tjhei), I've worked a lot on the interface and details of candi, such that your points:
* Generation of a simple, source-able environment.sh that exports directories of installed libraries (TRILINOS_DIR, DEAL_II_DIR, ...)
is done, by default, all packages creates their source-able file into $PROJECT/share/configuration

* Some way to select between minimal/default/everything regarding dependencies. I don't think there needs to be a way to en/disable individual packages, though. Let's keep it simple.
is done, the user can now switch on/off packages in the main configuration file (candi.cfg)

* Select mpicxx, etc. automatically if they exist and the user is not setting them, because this the right thing to do on nearly every platform.
is done, candi now searches for mpi-compilers and set them as default automatically (warning will be presented)

**Comment by koecher** [comment]
Anything more todo?

I think a "DEVELOPER_MODE" is useful, such that the package fetch/unpack/patching will be disabled to change files, e.g. source files of deal.II, and use candi to recompile. Do you like that?

**Comment by tjhei** [comment]
Cool stuff, thanks for all your work. I have been too busy (and will be over the next two weeks) to work on this more. I tried your changes where I can select/unselect certain packages and that worked great!

> I think a "DEVELOPER_MODE" is useful, such that the package fetch/unpack/patching will be disabled to change files, e.g. source files of deal.II, and use candi to recompile. Do you like that?

Personally, I don't think this is very important. The way I am using candi is that I let it install all dependencies and then I install deal.II manually the way I need it (different compilers/settings/folders/etc.). I don't think you will be able to incorporate all the workflows we developers use. I have always more than one copy of the source and many different installations lying around.

**Comment by Rombur** [comment]
@koecher is the new interface stable? If so I will add a page in deal.II wiki on how to use candi.

**Comment by koecher** [comment]
@Rombur more or less, this depends on a official announcement of candi as installer (would be nice to have it on github/dealii/candi)
I need to test the latest changes in my virtualboxes and then it would be. Documentation is needed.

@tjhei Okay, anyone is using some different build. Anyway I think this is useful and it is included (skipping fetch & unpack) in the current version v0.8.3 if forced. But you are right, it is not really important (does not work for specific build overwrites of a package without changing the package file).
* "I don't think you will be able to incorporate all the workflows we developers use. I have always more  than one copy of the source and many different installations lying around."

same for me :)
