### ISSUE TITLE
Installing Deal.II on manjaro using candi

### ISSUE THREAD

**Issue by sajed-zarrinpour** [koecher/candi#84]
Hello.
I know there is a package in the AUR for that, also I have the compiling from the source option. the problem is both methods were failed due to memory limitations. now I want to try your script and it tells me **Error: Your operating system could not be automatically recognised.**I would appreciate it if you save me from the trouble to find a _similar_ platform.
thank you

**Comment by tjhei** [comment]
What does ``lsb_release -a`` and ``cat /etc/os-release`` report for you?

**Comment by koecher** [comment]
Regarding wikipedia, manjaro linux is a derivate of arch linux.

Unfortunately, we don't have support for arch linux so far, i.e. detailed installation details in front of the run of candi to guarantee a perfect build experience.

Since v19.0 of Manjaro seems to be the latest stable release, it would be great if you can submit a pull request after a successful build; cf. https://en.wikipedia.org/wiki/Manjaro

I recommend to force the `platforms/supported/centos7.platform` and check if you have similar packages to install from your manjaro system for (at least):
- global development tools group install (e.g. `git`, `cmake`, `autotools` (make); `gcc`, `g++`, fortran compilers and corresponding `openmpi` or `mpich` compilers; and development packages like header files, etc)
- `blas`, `lapack` (and development packages like header files)
- `lua` (and development packages like header files)

The packages `doxygen`, `graphviz` and `qt-devel` should be optional.

**Comment by tjhei** [comment]
I have a basic working version already. Will open a PR in a minute.

**Comment by koecher** [comment]
@tjhei please merge yourself the platform, whenever you are ready.

**Comment by tjhei** [comment]
see https://github.com/dealii/candi/pull/136

**Comment by sajed-zarrinpour** [comment]
Sorry for the late reply guys.
@tjhei 
$ lsb_release -a 

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	19.0.2
Codename:	Kyria
----------------------------------------------------------------------------------------------------------------------------------
$ cat /etc/os-release

NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
-----------------------------------------------------------------------------------------------------------------------------
@koecher , I'm on it.

**Comment by tjhei** [comment]
Can you try if  https://github.com/dealii/candi/pull/136 works for you?

**Comment by sajed-zarrinpour** [comment]
well done about the pull request. but unfortunately, this is going to be a nightmare. the problem is with the trilions package. it requires GCC 4.7.x, my GCC is 9.2.1! I am trying to install that package individually and retry about installing deal-ii.

**Comment by tjhei** [comment]
> trilions package. it requires GCC 4.7.x, my GCC is 9.2.1

I doubt that this is true. What is the error you are seeing?

**Comment by koecher** [comment]
no answer for a long time.
